name: CI-auto_merge
on:
 push:
 branches: [ develop ]
jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - name: Starging a message
 run: echo Auto merge Started.
 - name: automerge
 uses: "pascalgn/automerge-action@v0.14.3"
 env:
 GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
 - name: Ending a message
 run: echo Auto merge Ended.
